import Head from "next/head";
import styles from "@/styles/Home.module.css";

import { Moon, LunarPhase } from "@/lib/moon";
import { format } from "date-fns";

export default function Home() {
  const nextFullMoon = format(
    Moon.nextLunarPhase(LunarPhase.FULL),
    "yyyy/MM/dd"
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Mooniversary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{nextFullMoon}</h1>
        <p className={styles.description}>is our next Mooniversary</p>
      </main>
    </div>
  );
}
