name: ci
on: [deployment_status]
jobs:
  e2e:
    # only runs this job on successful deploy
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Print URL 🖨
        run: echo Testing URL ${{ github.event.deployment_status.target_url }}

      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Run Cypress 🌲
        uses: cypress-io/github-action@v2
        with:
          record: true
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
