name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          record: true
          tag: main
          group: main
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - run: nyc report --reporter=text-summary --check-coverage
