name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          record: true
          tag: main
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
