name: preview
on: [deployment_status]
jobs:
  test-preview:
    # only runs this job on successful deploy
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.0
        name: Set timezone
        with:
          timezoneLinux: "America/Edmonton"

      - run: echo Preview URL ${{ github.event.deployment_status.target_url }}
        name: Print preview url

      - uses: actions/checkout@v2
        name: Checkout

      - uses: cypress-io/github-action@v2
        name: Run Cypress
        with:
          record: true
          tag: preview
          group: preview
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
